### ISSUE TITLE
hpm files need to be updated

### ISSUE THREAD

**Issue by Este1le** [kevinduh/sockeye-recipes3#2]
Need to update the hyper-parameters in example hpm files. Figure out what important hyperparameters and default configurations are. Consider including two hpm files with different sets of hyperparameters, one with minimal settings, one with comprehensive configurations. The former is for regular training, while the latter is for automl.

**Comment by kevinduh** [comment]
The minimal set of hyperparameters have been decided and can be seen in `hpm/*.hpm-template`. For comprehensive configurations, we will use the `$EXTRA_ARG` in `scripts/train.sh` to specify from command line. (Note, `scripts/train-textformat.sh` does not support extra arguments, and is meant to be simple for basic use.)
